########################################
# prompt global settings
########################################

# document link: https://starship.rs/ja-JP/config/#%E3%83%95%E3%82%9A%E3%83%AD%E3%83%B3%E3%83%95%E3%82%9A%E3%83%88
# format = "$all"
format = """
$cmd_duration \
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$golang\
$python\
$rust\
$julia\
$nodejs\
$bun\
$deno\
$lua\
$ocaml\
$swift\
$java\
$c\
$custom\
$cpp\
$zig\
$elixir\
$erlang\
$gleam\n\
$status$character
"""
add_newline = true


########################################
# prompt detail settings
########################################
[c]
detect_files = ["Makefile"]

[custom.cpp]
detect_extensions = ['cpp', 'cc', 'hpp']
detect_files = ["Makefile"]
symbol = "C++ "
format = "via [$symbol(v$output)-gcc]($style)"
command = "g++ --version | awk 'NR==1 {print $3}'"
style = "bold 149"
disabled = false
ignore_timeout = false



[fill]
symbol = " "
style = ""

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[$duration]($style)"

[username]
disabled = false
show_always = true
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style)"

[directory]
truncation_length = 0
truncate_to_repo = false


[status]
symbol = '[($status)](bold red)'
format = '$symbol'
map_symbol = false
disabled = false


[line_break]
disabled = true # separate prompt into 2 lines

[character]
disabled = false
success_symbol = "[>](bold green)" 
error_symbol = ""


########################################
# disabled: prompt detail settings
########################################

